idaproject_assignment/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

from django.urls.conf import re_path
from django.views.static import serve


urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('', include('pic_exchange.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pic_exchange/urls.py
from django.urls import path
from . import views

app_name = 'pic_exchange'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.PictureDetailedView.as_view(), name='detailed'),
    path('create', views.PictureCreateView.as_view(), name='create'),
    path('delete/<int:pk>', views.PictureDeleteView.as_view(), name='delete'),
]

pic_exchange/models.py
from django.db import models
from PIL import Image
from io import BytesIO
from django.core.files import File
import os

# Create your models here.
class Picture(models.Model):
    name = models.CharField(max_length=512)

    original_picture = models.ImageField(
        upload_to='site_media', editable=True, 
        width_field='original_width', height_field='original_height',)
    original_width = models.IntegerField(null=True)
    original_height = models.IntegerField(null=True)
    sized_picture = models.ImageField(upload_to='site_media', null=True, editable=True)
    content_type = models.CharField(max_length = 256, blank=True)

    max_width = 2048
    max_height = max_width
    max_size = max_width * max_height

    def __str__(self):
        return self.name

    def get_pic(self):
        pic = self.sized_picture if self.sized_picture else self.original_picture
        return pic

    def resize(self, width=None, height=None):
        image = Image.open(self.original_picture)
        ratio = self.original_width/self.original_height
        if not height or (width and width >= int(height*ratio)):
            image = image.resize((width, int(width/ratio)))
        else:
            image = image.resize((int(height*ratio), height))

        pic_io = BytesIO()
        image.save(pic_io, 'JPEG') 
        if self.sized_picture:
            self.sized_picture.delete()
        self.sized_picture = File(pic_io, f'{self.name}_sized.jpeg')

        self.save()

    def delete(self):
        self.original_picture.delete()
        self.sized_picture.delete()
        return super().delete()

pic_exchange/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Picture
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.files import File
from io import BytesIO
from urllib.request import urlopen
from PIL import Image

class PicForm(forms.ModelForm):
    original_picture = forms.FileField(required=False, label='Picture')
    upload_field_name = 'original_picture'
    link_picture = forms.CharField(required=False, label='Link')

    class Meta:
        model = Picture
        fields = ['name', 'original_picture', 'link_picture']

    def clean(self):
        cleaned = super().clean()
        pic = cleaned.get('original_picture')
        pic_link = cleaned.get('link_picture')
        print('PIC_LINK:', pic_link)
        if pic:
            if pic_link:
                raise ValidationError('Only one source of the file should be provided')
            if len(pic) > Picture.max_size:
                raise ValidationError("Your file is big, It's very-very big!")
        elif pic_link:
            try:
                url_str = self.cleaned_data.get('link_picture')
                url_pic = urlopen(url_str)
                pic_io = BytesIO()
                pic_io.write(url_pic.read())
                file = File(pic_io, url_str.split('/')[-1])
                image = Image.open(file)
                if image.width > Picture.max_width or image.height > Picture.max_height:
                    raise ValidationError("Your file is big, It's very-very big!")
                cleaned['link_picture'] = file
            except:
                raise ValidationError("Bad url provided")
        else:
            raise ValidationError("Either file or a link should be provided")

    def save(self, commit=True):
        pic_inst = super().save(commit=False)
        if self.cleaned_data.get('link_picture'):
            
            pic_inst.original_picture = self.cleaned_data.get('link_picture')
        else:
            picture = pic_inst.original_picture
            if isinstance(picture, InMemoryUploadedFile):
                loaded = picture.read()
                pic_inst.original_picture = loaded
                pic_inst.sized_picture = None
                pic_inst.content_type = picture.content_type
        
        if commit:
            pic_inst.save()
        return pic_inst


class ResizeForm(forms.Form):
    width = forms.IntegerField(max_value=Picture.max_width, min_value=1, required=False)
    height = forms.IntegerField(max_value=Picture.max_height, min_value=1, required=False)

    def clean(self):
        cleaned = super().clean()
        if not (cleaned.get('width') or cleaned.get('height')):
            raise ValidationError('Either width or height field should be fieled!')

pic_exchange/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.urls.base import reverse_lazy
from django.utils.translation import templatize
from django.shortcuts import get_object_or_404
from django.views.generic import View, DeleteView
from django.http import HttpResponse
from .models import Picture
from .forms import PicForm, ResizeForm

# Create your views here.
class IndexView(View):
    template_name = 'pic_exchange/index.html'

    def get(self, request):
        pictures = Picture.objects.all()
        context = {
            'pictures': pictures,
        }
        return render(request, self.template_name, context)


class PictureDetailedView(View):
    template_name = 'pic_exchange/pic_detailed.html'

    def get(self, request, pk):
        pic = get_object_or_404(Picture, pk=pk)
        form = ResizeForm
        context = {
            'picture': pic,
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        pic = get_object_or_404(Picture, pk=pk)
        form = ResizeForm(request.POST)
        if not form.is_valid():
            context = {'picture':pic, 'form': form}
            return render(request, self.template_name, context)
        cleaned = form.cleaned_data
        pic.resize(cleaned['width'] or None, cleaned['height'] or None)
        pic.save()
        return redirect('pic_exchange:detailed', pic.pk)
        

class PictureCreateView(View):
    template_name = 'pic_exchange/pic_create.html'
    
    def get(self, request):
        form = PicForm()
        context = {
            'form': form,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = PicForm(request.POST, request.FILES)
        if not form.is_valid():
            context = {'form': form,}
            return render(request, self.template_name, context)
        picture = form.save()
        return redirect('pic_exchange:detailed', picture.pk)


class PictureDeleteView(DeleteView):
    model = Picture
    success_url = reverse_lazy('pic_exchange:index')
    template_name = 'pic_exchange/pic_delete.html'

pic_exchange/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>{% block title %}
        Fabrique polls app
    {% endblock %}</title>
  </head>
  <body>
    <div style="max-width: 1000px; margin: auto">
    
        {% block content %}
            <h1>It's a base template</h1>
        {% endblock %}
    </div>
  </body>
</html>

pic_exchange/templates/pic_exchange/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>All pictures</h1>
    {% if pictures %}
    <ul>
        {% for picture in pictures %}
        <li>
            <a href="{% url 'pic_exchange:detailed' picture.pk %}">{{ picture.name }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <h4>No pictures yet</h4>
    {% endif %}
    <a href="{% url 'pic_exchange:create' %}">Upload new picture</a>
{% endblock %}

pic_exchange/templates/pic_exchange/pic_create.html
{% extends 'base.html' %}

{% block content %}
    <h1>Creating a picture</h1>
    <form method='POST' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" />
        <a href="{% url 'pic_exchange:index' %}">Back</a>
    </form>
{% endblock %}

pic_exchange/templates/pic_exchange/pic_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Are you sure you want to delete this picture?</h1>
    <h3>{{ picture.name }}</h3>
    <img src="{{ picture.get_pic.url }}" style="max-width: 1000px; max-height: 1000px;"/>
    <form method='POST'>
        {% csrf_token %}
        <input type="submit" value="Delete" />
    </form>
    <p><a href="{% url 'pic_exchange:detailed' picture.pk %}">Back</a></p>
{% endblock %}

pic_exchange/templates/pic_exchange/pic_detailed.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ picture.name }}</h1>
    <img src="{{ picture.get_pic.url }}" style="max-width: 1000px; max-height: 1000px;"/>
    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Resize" />
    </form>
    <p><a href="{% url 'pic_exchange:index' %}">Back</a></p>
    <p><a href="{% url 'pic_exchange:delete' picture.pk %}">Delete</a></p>
{% endblock %}